import type { PaletteColor } from "./color";
import { readableTextColor } from "./color";

const APP_NAME = "Color Catcher by VforUs";
const ROLE_LABELS = {
  zh: {
    neutral: "中性色",
    primary: "主色",
    secondary: "辅助色",
    accent: "点缀色"
  },
  en: {
    neutral: "Neutral",
    primary: "Primary",
    secondary: "Secondary",
    accent: "Accent"
  }
} as const;

export function exportPalettePng(colors: PaletteColor[], title: string, language: keyof typeof ROLE_LABELS = "en") {
  const canvas = document.createElement("canvas");
  const width = 1600;
  const height = 2000;
  const padding = 112;
  const context = canvas.getContext("2d");

  if (!context) {
    throw new Error("This browser cannot generate the palette image.");
  }

  canvas.width = width;
  canvas.height = height;

  context.fillStyle = "#F4F6F1";
  context.fillRect(0, 0, width, height);

  context.fillStyle = "#202426";
  context.font = "700 72px Arial, sans-serif";
  context.fillText(APP_NAME, padding, 152);

  context.font = "400 34px Arial, sans-serif";
  context.fillStyle = "#68706B";
  context.fillText(title || "Uploaded image", padding, 214);

  const top = 320;
  const swatchHeight = Math.floor((height - top - padding) / colors.length);

  colors.forEach((color, index) => {
    const y = top + index * swatchHeight;
    const blockHeight = swatchHeight - 22;
    const textColor = readableTextColor(color.rgb);

    context.fillStyle = color.hex;
    roundedRect(context, padding, y, width - padding * 2, blockHeight, 28);
    context.fill();

    context.fillStyle = textColor;
    context.font = "700 52px Arial, sans-serif";
    context.fillText(color.hex, padding + 48, y + 78);

    context.font = "400 28px Arial, sans-serif";
    context.fillText(ROLE_LABELS[language][color.role as keyof typeof ROLE_LABELS.en] || color.role, padding + 48, y + 126);
    context.fillText(`RGB ${color.rgb.r}, ${color.rgb.g}, ${color.rgb.b}`, padding + 48, y + 174);
    context.fillText(`HSL ${color.hsl.h}, ${color.hsl.s}%, ${color.hsl.l}%`, padding + 48, y + 222);

    context.font = "700 38px Arial, sans-serif";
    context.textAlign = "right";
    context.fillText(`${Math.round(color.percentage * 100)}%`, width - padding - 48, y + 86);
    context.textAlign = "left";
  });

  context.fillStyle = "#68706B";
  context.font = "400 26px Arial, sans-serif";
  context.fillText(`Generated by ${APP_NAME}`, padding, height - 54);

  const link = document.createElement("a");
  link.download = `${safeFileName(title || "color-catcher-by-vforus")}-palette.png`;
  link.href = canvas.toDataURL("image/png");
  link.click();
}

function roundedRect(
  context: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number
) {
  context.beginPath();
  context.moveTo(x + radius, y);
  context.arcTo(x + width, y, x + width, y + height, radius);
  context.arcTo(x + width, y + height, x, y + height, radius);
  context.arcTo(x, y + height, x, y, radius);
  context.arcTo(x, y, x + width, y, radius);
  context.closePath();
}

function safeFileName(value: string) {
  return value
    .toLowerCase()
    .replace(/\.[a-z0-9]+$/i, "")
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}
